# Generated by Django 4.0.5 on 2022-06-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_slug_alter_category_title_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='package_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6),
        ),
    ]
